server:
  port: ${PORT_TO_EXPOSE:8081}

logging:
  level:
    ROOT: INFO
    org.springframework: INFO

spring:
  flyway:
    enabled: false
  application:
    name: study
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/advertisement_db?currentSchema=advertisement_schema
    username: postgres
    password: postgres
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

secure:
  signingKey: $2a$12$7tlfo74qWmwaNQDzW3B09OA4Okw3m6rsA04aua/v9dg4nfwQ7k5SK

springfox:
  documentation:
    swagger:
      v2:
        path: /v3/api-docs