-- Removes all rows from a table or specified partitions of a table, without logging the individual row deletions.
TRUNCATE TABLE CATEGORY CASCADE;

-- Insert Data into columns
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (1, now(), NULL, 'FromMigrationCategory', 0);

INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (2, now(), NULL, 'Транспорт', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (3, now(), NULL, 'Автомобили', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (4, now(), NULL, 'Мотоциклы и мототехника', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (5, now(), NULL, 'Грузовики и спецтехника', 0);

INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (6, now(), NULL, 'Недвижимость', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (7, now(), NULL, 'Квартиры', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (8, now(), NULL, 'Комнаты', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (9, now(), NULL, 'Дома, дачи, коттеджи', 0);

INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (10, now(), NULL, 'Электроника', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (11, now(), NULL, 'Аудио и видео', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (12, now(), NULL, 'Игры, приставки и программы', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (13, now(), NULL, 'Настольные компьютеры', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (14, now(), NULL, 'Ноутбуки', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (15, now(), NULL, 'Планшеты и электронные книги', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (16, now(), NULL, 'Телефоны', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (17, now(), NULL, 'Товары для компьютера', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (18, now(), NULL, 'Фототехника', 0);

INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (19, now(), NULL, 'Искусство', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (20, now(), NULL, 'Живопись маслом', 0);
INSERT INTO CATEGORY (ID, CREATED_AT, UPDATED_AT, NAME, STATUS) VALUES (21, now(), NULL, 'Акварель', 0);