-- Add column
ALTER TABLE ADVERTISEMENT ADD COLUMN CATEGORY_ID BIGINT;
-- Add reference
ALTER TABLE ADVERTISEMENT ADD CONSTRAINT ADVERTISEMENT_FKEY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID);
